import pickle

occ_code = \
{
    10: 'Chief executives',
    20: 'General and operations managers',
    30: 'Legislators',
    40: 'Advertising and promotions managers',
    50: 'Marketing and sales managers',
    60: 'Public relations managers',
    100: 'Administrative services managers',
    110: 'Computer and information systems managers',
    120: 'Financial managers',
    130: 'Human resources managers',
    140: 'Industrial production managers',
    150: 'Purchasing managers',
    160: 'Transportation, storage, and distribution managers',
    200: 'Farm, ranch, and other agricultural managers',
    210: 'Farmers and ranchers',
    220: 'Construction managers',
    230: 'Education administrators',
    300: 'Engineering managers',
    310: 'Food service managers',
    320: 'Funeral directors',
    330: 'Gaming managers',
    340: 'Lodging managers',
    350: 'Medical and health services managers',
    360: 'Natural sciences managers',
    400: 'Postmasters and mail superintendents',
    410: 'Property, real estate, and community association managers',
    420: 'Social and community service managers',
    430: 'Managers, all other',
    500: 'Agents and business managers of artists, performers, and athletes',
    510: 'Purchasing agents and buyers, farm products',
    520: 'Wholesale and retail buyers, except farm products',
    530: 'Purchasing agents, except wholesale, retail, and farm products',
    540: 'Claims adjusters, appraisers, examiners, and investigators',
    560: 'Compliance officers, except agriculture, construction, health and safety, and transportation',
    600: 'Cost estimators',
    620: 'Human resources, training, and labor relations specialists',
    700: 'Logisticians',
    710: 'Management analysts',
    720: 'Meeting and convention planners',
    730: 'Other business operations specialists',
    800: 'Accountants and auditors',
    810: 'Appraisers and assessors of real estate',
    820: 'Budget analysts',
    830: 'Credit analysts',
    840: 'Financial analysts',
    850: 'Personal financial advisors',
    860: 'Insurance underwriters',
    900: 'Financial examiners',
    910: 'Loan counselors and officers',
    930: 'Tax examiners, collectors, and revenue agents',
    940: 'Tax preparers',
    950: 'Financial specialists, all other',
    1000: 'Computer scientists and systems analysts',
    1010: 'Computer programmers',
    1020: 'Computer software engineers',
    1040: 'Computer support specialists',
    1060: 'Database administrators',
    1100: 'Network and computer systems administrators',
    1110: 'Network systems and data communications analysts',
    1200: 'Actuaries',
    1210: 'Mathematicians',
    1220: 'Operations research analysts',
    1230: 'Statisticians',
    1240: 'Miscellaneous mathematical science occupations',
    1300: 'Architects, except naval',
    1310: 'Surveyors, cartographers, and photogrammetrists',
    1320: 'Aerospace engineers',
    1330: 'Agricultural engineers',
    1340: 'Biomedical engineers',
    1350: 'Chemical engineers',
    1360: 'Civil engineers',
    1400: 'Computer hardware engineers',
    1410: 'Electrical and electronic engineers',
    1420: 'Environmental engineers',
    1430: 'Industrial engineers, including health and safety',
    1440: 'Marine engineers and naval architects',
    1450: 'Materials engineers',
    1460: 'Mechanical engineers',
    1500: 'Mining and geological engineers, including mining safety engineers',
    1510: 'Nuclear engineers',
    1520: 'Petroleum engineers',
    1530: 'Engineers, all other',
    1540: 'Drafters',
    1550: 'Engineering technicians, except drafters',
    1560: 'Surveying and mapping technicians',
    1600: 'Agricultural and food scientists',
    1610: 'Biological scientists',
    1640: 'Conservation scientists and foresters',
    1650: 'Medical scientists',
    1700: 'Astronomers and physicists',
    1710: 'Atmospheric and space scientists',
    1720: 'Chemists and materials scientists',
    1740: 'Environmental scientists and geoscientists',
    1760: 'Physical scientists, all other',
    1800: 'Economists',
    1810: 'Market and survey researchers',
    1820: 'Psychologists',
    1830: 'Sociologists',
    1840: 'Urban and regional planners',
    1860: 'Miscellaneous social scientists and related workers',
    1900: 'Agricultural and food science technicians',
    1910: 'Biological technicians',
    1920: 'Chemical technicians',
    1930: 'Geological and petroleum technicians',
    1940: 'Nuclear technicians',
    1960: 'Other life, physical, and social science technicians',
    2000: 'Counselors',
    2010: 'Social workers',
    2020: 'Miscellaneous community and social service specialists',
    2040: 'Clergy',
    2050: 'Directors, religious activities and education',
    2060: 'Religious workers, all other',
    2100: 'Lawyers',
    2110: 'Judges, magistrates, and other judicial workers',
    2140: 'Paralegals and legal assistants',
    2150: 'Miscellaneous legal support workers',
    2200: 'Postsecondary teachers',
    2300: 'Preschool and kindergarten teachers',
    2310: 'Elementary and middle school teachers',
    2320: 'Secondary school teachers',
    2330: 'Special education teachers',
    2340: 'Other teachers and instructors',
    2400: 'Archivists, curators, and museum technicians',
    2430: 'Librarians',
    2440: 'Library technicians',
    2540: 'Teacher assistants',
    2550: 'Other education, training, and library workers',
    2600: 'Artists and related workers',
    2630: 'Designers',
    2700: 'Actors',
    2710: 'Producers and directors',
    2720: 'Athletes, coaches, umpires, and related workers',
    2740: 'Dancers and choreographers',
    2750: 'Musicians, singers, and related workers',
    2760: 'Entertainers and performers, sports and related workers, all other',
    2800: 'Announcers',
    2810: 'News analysts, reporters and correspondents',
    2820: 'Public relations specialists',
    2830: 'Editors',
    2840: 'Technical writers',
    2850: 'Writers and authors',
    2860: 'Miscellaneous media and communication workers',
    2900: 'Broadcast and sound engineering technicians and radio operators',
    2910: 'Photographers',
    2920: 'Television, video, and motion picture camera operators and editors',
    2960: 'Media and communication equipment workers, all other',
    3000: 'Chiropractors',
    3010: 'Dentists',
    3030: 'Dietitians and nutritionists',
    3040: 'Optometrists',
    3050: 'Pharmacists',
    3060: 'Physicians and surgeons',
    3110: 'Physician assistants',
    3120: 'Podiatrists',
    3130: 'Registered nurses',
    3140: 'Audiologists',
    3150: 'Occupational therapists',
    3160: 'Physical therapists',
    3200: 'Radiation therapists',
    3210: 'Recreational therapists',
    3220: 'Respiratory therapists',
    3230: 'Speech-language pathologists',
    3240: 'Therapists, all other',
    3250: 'Veterinarians',
    3260: 'Health diagnosing and treating practitioners, all other',
    3300: 'Clinical laboratory technologists and technicians',
    3310: 'Dental hygienists',
    3320: 'Diagnostic related technologists and technicians',
    3400: 'Emergency medical technicians and paramedics',
    3410: 'Health diagnosing and treating practitioner support technicians',
    3500: 'Licensed practical and licensed vocational nurses',
    3510: 'Medical records and health information technicians',
    3520: 'Opticians, dispensing',
    3530: 'Miscellaneous health technologists and technicians',
    3540: 'Other healthcare practitioners and technical occupations',
    3600: 'Nursing, psychiatric, and home health aides',
    3610: 'Occupational therapist assistants and aides',
    3620: 'Physical therapist assistants and aides',
    3630: 'Massage therapists',
    3640: 'Dental assistants',
    3650: 'Medical assistants and other healthcare support occupations',
    3700: 'First-line supervisors/managers of correctional officers',
    3710: 'First-line supervisors/managers of police and detectives',
    3720: 'First-line supervisors/managers of fire fighting and prevention workers',
    3730: 'Supervisors, protective service workers, all other',
    3740: 'Fire fighters',
    3750: 'Fire inspectors',
    3800: 'Bailiffs, correctional officers, and jailers',
    3820: 'Detectives and criminal investigators',
    3830: 'Fish and game wardens',
    3840: 'Parking enforcement workers',
    3850: 'Police and sheriff\'s patrol officers',
    3860: 'Transit and railroad police',
    3900: 'Animal control workers',
    3910: 'Private detectives and investigators',
    3920: 'Security guards and gaming surveillance officers',
    3940: 'Crossing guards',
    3950: 'Lifeguards and other protective service workers',
    4000: 'Chefs and head cooks',
    4010: 'First-line supervisors/managers of food preparation and serving workers',
    4020: 'Cooks',
    4030: 'Food preparation workers',
    4040: 'Bartenders',
    4050: 'Combined food preparation and serving workers, including fast food',
    4060: 'Counter attendants, cafeteria, food concession, and coffee shop',
    4110: 'Waiters and waitresses',
    4120: 'Food servers, nonrestaurant',
    4130: 'Dining room and cafeteria attendants and bartender helpers',
    4140: 'Dishwashers',
    4150: 'Hosts and hostesses, restaurant, lounge, and coffee shop',
    4160: 'Food preparation and serving related workers, all other',
    4200: 'First-line supervisors/managers of housekeeping and janitorial workers',
    4210: 'First-line supervisors/managers of landscaping, lawn service, and groundskeeping workers',
    4220: 'Janitors and building cleaners',
    4230: 'Maids and housekeeping cleaners',
    4240: 'Pest control workers',
    4250: 'Grounds maintenance workers',
    4300: 'First-line supervisors/managers of gaming workers',
    4320: 'First-line supervisors/managers of personal service workers',
    4340: 'Animal trainers',
    4350: 'Nonfarm animal caretakers',
    4400: 'Gaming services workers',
    4410: 'Motion picture projectionists',
    4420: 'Ushers, lobby attendants, and ticket takers',
    4430: 'Miscellaneous entertainment attendants and related workers',
    4460: 'Funeral service workers',
    4500: 'Barbers',
    4510: 'Hairdressers, hairstylists, and cosmetologists',
    4520: 'Miscellaneous personal appearance workers',
    4530: 'Baggage porters, bellhops, and concierges',
    4540: 'Tour and travel guides',
    4550: 'Transportation attendants',
    4600: 'Child care workers',
    4610: 'Personal and home care aides',
    4620: 'Recreation and fitness workers',
    4640: 'Residential advisors',
    4650: 'Personal care and service workers, all other ',
    4700: 'First-line supervisors/managers of retail sales workers',
    4710: 'First-line supervisors/managers of non-retail sales workers',
    4720: 'Cashiers',
    4740: 'Counter and rental clerks',
    4750: 'Parts salespersons',
    4760: 'Retail salespersons',
    4800: 'Advertising sales agents',
    4810: 'Insurance sales agents',
    4820: 'Securities, commodities, and financial services sales agents',
    4830: 'Travel agents',
    4840: 'Sales representatives, services, all other',
    4850: 'Sales representatives, wholesale and manufacturing',
    4900: 'Models, demonstrators, and product promoters',
    4920: 'Real estate brokers and sales agents',
    4930: 'Sales engineers',
    4940: 'Telemarketers',
    4950: 'Door-to-door sales workers, news and street vendors, and related workers',
    4960: 'Sales and related workers, all other',
    5000: 'First-line supervisors/managers of office and administrative support workers',
    5010: 'Switchboard operators, including answering service',
    5020: 'Telephone operators',
    5030: 'Communications equipment operators, all other',
    5100: 'Bill and account collectors',
    5110: 'Billing and posting clerks and machine operators',
    5120: 'Bookkeeping, accounting, and auditing clerks',
    5130: 'Gaming cage workers',
    5140: 'Payroll and timekeeping clerks',
    5150: 'Procurement clerks',
    5160: 'Tellers',
    5200: 'Brokerage clerks',
    5210: 'Correspondence clerks',
    5220: 'Court, municipal, and license clerks',
    5230: 'Credit authorizers, checkers, and clerks',
    5240: 'Customer service representatives',
    5250: 'Eligibility interviewers, government programs',
    5260: 'File Clerks',
    5300: 'Hotel, motel, and resort desk clerks',
    5310: 'Interviewers, except eligibility and loan',
    5320: 'Library assistants, clerical',
    5330: 'Loan interviewers and clerks',
    5340: 'New accounts clerks',
    5350: 'Order clerks',
    5360: 'Human resources assistants, except payroll and timekeeping',
    5400: 'Receptionists and information clerks',
    5410: 'Reservation and transportation ticket agents and travel clerks',
    5420: 'Information and record clerks, all other',
    5500: 'Cargo and freight agents',
    5510: 'Couriers and messengers',
    5520: 'Dispatchers',
    5530: 'Meter readers, utilities',
    5540: 'Postal service clerks',
    5550: 'Postal service mail carriers',
    5560: 'Postal service mail sorters, processors, and processing machine operators',
    5600: 'Production, planning, and expediting clerks',
    5610: 'Shipping, receiving, and traffic clerks',
    5620: 'Stock clerks and order fillers',
    5630: 'Weighers, measurers, checkers, and samplers, recordkeeping',
    5700: 'Secretaries and administrative assistants',
    5800: 'Computer operators',
    5810: 'Data entry keyers',
    5820: 'Word processors and typists',
    5830: 'Desktop publishers',
    5840: 'Insurance claims and policy processing clerks',
    5850: 'Mail clerks and mail machine operators, except postal service',
    5860: 'Office clerks, general',
    5900: 'Office machine operators, except computer',
    5910: 'Proofreaders and copy markers',
    5920: 'Statistical assistants',
    5930: 'Office and administrative support workers, all other',
    6000: 'First-line supervisors/managers of farming, fishing, and forestry workers',
    6010: 'Agricultural inspectors',
    6020: 'Animal breeders',
    6040: 'Graders and sorters, agricultural products',
    6050: 'Miscellaneous agricultural workers ',
    6100: 'Fishers and related fishing workers',
    6110: 'Hunters and trappers',
    6120: 'Forest and conservation workers',
    6130: 'Logging workers',
    6200: 'First-line supervisors/managers of construction trades and extraction workers',
    6210: 'Boilermakers',
    6220: 'Brickmasons, blockmasons, and stonemasons',
    6230: 'Carpenters',
    6240: 'Carpet, floor, and tile installers and finishers',
    6250: 'Cement masons, concrete finishers, and terrazzo workers',
    6260: 'Construction laborers',
    6300: 'Paving, surfacing, and tamping equipment operators',
    6310: 'Pile-driver operators',
    6320: 'Operating engineers and other construction equipment operators',
    6330: 'Drywall installers, ceiling tile installers, and tapers',
    6350: 'Electricians',
    6360: 'Glaziers',
    6400: 'Insulation workers',
    6420: 'Painters, construction and maintenance',
    6430: 'Paperhangers',
    6440: 'Pipelayers, plumbers, pipefitters, and steamfitters',
    6460: 'Plasterers and stucco masons',
    6500: 'Reinforcing iron and rebar workers',
    6510: 'Roofers',
    6520: 'Sheet metal workers',
    6530: 'Structural iron and steel workers',
    6600: 'Helpers, construction trades',
    6660: 'Construction and building inspectors',
    6700: 'Elevator installers and repairers',
    6710: 'Fence erectors',
    6720: 'Hazardous materials removal workers',
    6730: 'Highway maintenance workers',
    6740: 'Rail-track laying and maintenance equipment operators',
    6750: 'Septic tank servicers and sewer pipe cleaners',
    6760: 'Miscellaneous construction and related workers',
    6800: 'Derrick, rotary drill, and service unit operators, oil, gas, and mining',
    6820: 'Earth drillers, except oil and gas',
    6830: 'Explosives workers, ordnance handling experts, and blasters',
    6840: 'Mining machine operators',
    6910: 'Roof bolters, mining',
    6920: 'Roustabouts, oil and gas',
    6930: 'Helpers--extraction workers',
    6940: 'Other extraction workers',
    7000: 'First-line supervisors/managers of mechanics, installers, and repairers',
    7010: 'Computer, automated teller, and office machine repairers',
    7020: 'Radio and telecommunications equipment installers and repairers',
    7030: 'Avionics technicians',
    7040: 'Electric motor, power tool, and related repairers',
    7050: 'Electrical and electronics installers and repairers, transportation equipment',
    7100: 'Electrical and electronics repairers, industrial and utility',
    7110: 'Electronic equipment installers and repairers, motor vehicles',
    7120: 'Electronic home entertainment equipment installers and repairers',
    7130: 'Security and fire alarm systems installers',
    7140: 'Aircraft mechanics and service technicians',
    7150: 'Automotive body and related repairers',
    7160: 'Automotive glass installers and repairers',
    7200: 'Automotive service technicians and mechanics',
    7210: 'Bus and truck mechanics and diesel engine specialists',
    7220: 'Heavy vehicle and mobile equipment service technicians and mechanics',
    7240: 'Small engine mechanics',
    7260: 'Miscellaneous vehicle and mobile equipment mechanics, installers, and repairers',
    7300: 'Control and valve installers and repairers',
    7310: 'Heating, air conditioning, and refrigeration mechanics and installers',
    7320: 'Home appliance repairers',
    7330: 'Industrial and refractory machinery mechanics',
    7340: 'Maintenance and repair workers, general',
    7350: 'Maintenance workers, machinery',
    7360: 'Millwrights',
    7410: 'Electrical power-line installers and repairers',
    7420: 'Telecommunications line installers and repairers',
    7430: 'Precision instrument and equipment repairers',
    7510: 'Coin, vending, and amusement machine servicers and repairers',
    7520: 'Commercial divers',
    7540: 'Locksmiths and safe repairers',
    7550: 'Manufactured building and mobile home installers',
    7560: 'Riggers',
    7600: 'Signal and track switch repairers',
    7610: 'Helpers--installation, maintenance, and repair workers ',
    7620: 'Other installation, maintenance, and repair workers',
    7700: 'First-line supervisors/managers of production and operating workers',
    7710: 'Aircraft structure, surfaces, rigging, and systems assemblers',
    7720: 'Electrical, electronics, and electromechanical assemblers',
    7730: 'Engine and other machine assemblers',
    7740: 'Structural metal fabricators and fitters',
    7750: 'Miscellaneous assemblers and fabricators',
    7800: 'Bakers',
    7810: 'Butchers and other meat, poultry, and fish processing workers',
    7830: 'Food and tobacco roasting, baking, and drying machine operators and tenders',
    7840: 'Food batchmakers',
    7850: 'Food cooking machine operators and tenders',
    7900: 'Computer control programmers and operators',
    7920: 'Extruding and drawing machine setters, operators, and tenders, metal and plastic',
    7930: 'Forging machine setters, operators, and tenders, metal and plastic',
    7940: 'Rolling machine setters, operators, and tenders, metal and plastic',
    7950: 'Cutting, punching, and press machine setters, operators, and tenders, metal and plastic',
    7960: 'Drilling and boring machine tool setters, operators, and tenders, metal and plastic ',
    8000: 'Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic',
    8010: 'Lathe and turning machine tool setters, operators, and tenders, metal and plastic',
    8020: 'Milling and planing machine setters, operators, and tenders, metal and plastic',
    8030: 'Machinists',
    8040: 'Metal furnace and kiln operators and tenders',
    8060: 'Model makers and patternmakers, metal and plastic',
    8100: 'Molders and molding machine setters, operators, and tenders, metal and plastic',
    8120: 'Multiple machine tool setters, operators, and tenders, metal and plastic ',
    8130: 'Tool and die makers',
    8140: 'Welding, soldering, and brazing workers',
    8150: 'Heat treating equipment setters, operators, and tenders, metal and plastic',
    8160: 'Lay-out workers, metal and plastic',
    8200: 'Plating and coating machine setters, operators, and tenders, metal and plastic',
    8210: 'Tool grinders, filers, and sharpeners',
    8220: 'Metalworkers and plastic workers, all other',
    8230: 'Bookbinders and bindery workers',
    8240: 'Job printers',
    8250: 'Prepress technicians and workers',
    8260: 'Printing machine operators',
    8300: 'Laundry and dry-cleaning workers',
    8310: 'Pressers, textile, garment, and related materials',
    8320: 'Sewing machine operators',
    8330: 'Shoe and leather workers and repairers',
    8340: 'Shoe machine operators and tenders',
    8350: 'Tailors, dressmakers, and sewers',
    8360: 'Textile bleaching and dyeing machine operators and tenders',
    8400: 'Textile cutting machine setters, operators, and tenders',
    8410: 'Textile knitting and weaving machine setters, operators, and tenders',
    8420: 'Textile winding, twisting, and drawing out machine setters, operators, and tenders',
    8430: 'Extruding and forming machine setters, operators, and tenders, synthetic and glass fibers',
    8440: 'Fabric and apparel patternmakers',
    8450: 'Upholsterers',
    8460: 'Textile, apparel, and furnishings workers, all other',
    8500: 'Cabinetmakers and bench carpenters',
    8510: 'Furniture finishers',
    8520: 'Model makers and patternmakers, wood',
    8530: 'Sawing machine setters, operators, and tenders, wood',
    8540: 'Woodworking machine setters, operators, and tenders, except sawing',
    8550: 'Woodworkers, all other',
    8600: 'Power plant operators, distributors, and dispatchers',
    8610: 'Stationary engineers and boiler operators',
    8620: 'Water and liquid waste treatment plant and system operators',
    8630: 'Miscellaneous plant and system operators',
    8640: 'Chemical processing machine setters, operators, and tenders',
    8650: 'Crushing, grinding, polishing, mixing, and blending workers',
    8710: 'Cutting workers',
    8720: 'Extruding, forming, pressing, and compacting machine setters, operators, and tenders',
    8730: 'Furnace, kiln, oven, drier, and kettle operators and tenders',
    8740: 'Inspectors, testers, sorters, samplers, and weighers',
    8750: 'Jewelers and precious stone and metal workers',
    8760: 'Medical, dental, and ophthalmic laboratory technicians',
    8800: 'Packaging and filling machine operators and tenders',
    8810: 'Painting workers',
    8830: 'Photographic process workers and processing machine operators',
    8840: 'Semiconductor processors',
    8850: 'Cementing and gluing machine operators and tenders',
    8860: 'Cleaning, washing, and metal pickling equipment operators and tenders',
    8900: 'Cooling and freezing equipment operators and tenders',
    8910: 'Etchers and engravers',
    8920: 'Molders, shapers, and casters, except metal and plastic',
    8930: 'Paper goods machine setters, operators, and tenders',
    8940: 'Tire builders',
    8950: 'Helpers--production workers',
    8960: 'Production workers, all other',
    9000: 'Supervisors, transportation and material moving workers',
    9030: 'Aircraft pilots and flight engineers',
    9040: 'Air traffic controllers and airfield operations specialists',
    9110: 'Ambulance drivers and attendants, except emergency medical technicians',
    9120: 'Bus drivers',
    9130: 'Driver/sales workers and truck drivers',
    9140: 'Taxi drivers and chauffeurs',
    9150: 'Motor vehicle operators, all other',
    9200: 'Locomotive engineers and operators',
    9230: 'Railroad brake, signal, and switch operators',
    9240: 'Railroad conductors and yardmasters',
    9260: 'Subway, streetcar, and other rail transportation workers',
    9300: 'Sailors and marine oilers',
    9310: 'Ship and boat captains and operators',
    9330: 'Ship engineers',
    9340: 'Bridge and lock tenders',
    9350: 'Parking lot attendants',
    9360: 'Service station attendants',
    9410: 'Transportation inspectors',
    9420: 'Other transportation workers ',
    9500: 'Conveyor operators and tenders',
    9510: 'Crane and tower operators',
    9520: 'Dredge, excavating, and loading machine operators',
    9560: 'Hoist and winch operators',
    9600: 'Industrial truck and tractor operators',
    9610: 'Cleaners of vehicles and equipment',
    9620: 'Laborers and freight, stock, and material movers, hand',
    9630: 'Machine feeders and offbearers',
    9640: 'Packers and packagers, hand',
    9650: 'Pumping station operators',
    9720: 'Refuse and recyclable material collectors',
    9730: 'Shuttle car operators',
    9740: 'Tank car, truck, and ship loaders',
    9750: 'Material moving workers, all other',
    9800: 'Military officer special and tactical operations leaders/managers',
    9810: 'First-line enlisted military supervisors/managers',
    9820: 'Military enlisted tactical operations and air/weapons specialists and crew members',
    9830: 'Military, rank not specified',
    9920: 'Unemployed, last worked five years ago or earlier or never worked',
}

with open('occ_code.pkl', 'wb') as fp:
    pickle.dump(occ_code, fp)


occ = ['First-line supervisors/managers of office and administrative support workers',
       'Elementary and middle school teachers', 'Electricians',
       'Structural iron and steel workers', 'Special education teachers',
       'Human resources, training, and labor relations specialists',
       'Food batchmakers',
       'Carpet, floor, and tile installers and finishers', 'Carpenters',
       'Cooks', 'Financial managers', 'Postsecondary teachers',
       'Nursing, psychiatric, and home health aides',
       'Receptionists and information clerks',
       'Paralegals and legal assistants',
       'Cement masons, concrete finishers, and terrazzo workers',
       'Chief executives', 'Cashiers', 'Printing machine operators',
       'Engineers, all other', 'Social workers', 'Registered nurses',
       'Bill and account collectors',
       'Laborers and freight, stock, and material movers, hand',
       'Miscellaneous assemblers and fabricators',
       'First-line supervisors/managers of non-retail sales workers',
       'Food preparation workers', 'Surveying and mapping technicians',
       'Medical records and health information technicians',
       'Computer programmers', 'Secondary school teachers',
       'Medical and health services managers', 'Parts salespersons',
       'Operating engineers and other construction equipment operators',
       'First-line supervisors/managers of mechanics, installers, and repairers',
       'Shipping, receiving, and traffic clerks', 'Counselors',
       'Managers, all other', 'Data entry keyers',
       'Crane and tower operators',
       'Cutting, punching, and press machine setters, operators, and tenders, metal and plastic',
       'Massage therapists',
       'Electrical power-line installers and repairers',
       'Stock clerks and order fillers',
       'Secretaries and administrative assistants',
       'First-line supervisors/managers of retail sales workers',
       'Computer scientists and systems analysts',
       'Pipelayers, plumbers, pipefitters, and steamfitters',
       'First-line supervisors/managers of construction trades and extraction workers',
       'Security guards and gaming surveillance officers',
       'Health diagnosing and treating practitioner support technicians',
       'Bookkeeping, accounting, and auditing clerks',
       'Opticians, dispensing', 'Personal financial advisors',
       'Welding, soldering, and brazing workers', 'Teacher assistants',
       'Sales representatives, wholesale and manufacturing',
       'Waiters and waitresses', 'Retail salespersons',
       'Bus and truck mechanics and diesel engine specialists',
       'Dispatchers', 'Office clerks, general',
       'Loan interviewers and clerks',
       'Heating, air conditioning, and refrigeration mechanics and installers',
       'Driver/sales workers and truck drivers', 'Designers',
       'Combined food preparation and serving workers, including fast food',
       'Speech-language pathologists', 'Residential advisors',
       'First-line supervisors/managers of farming, fishing, and forestry workers',
       'Other healthcare practitioners and technical occupations',
       'Personal and home care aides',
       'Social and community service managers',
       'First-line supervisors/managers of production and operating workers',
       'Machinists', 'Civil engineers',
       'Customer service representatives',
       'Cleaners of vehicles and equipment',
       'Hazardous materials removal workers', 'Accountants and auditors',
       'Athletes, coaches, umpires, and related workers', 'Barbers',
       'Butchers and other meat, poultry, and fish processing workers',
       'Physicians and surgeons', "Police and sheriff's patrol officers",
       'Production workers, all other', 'Recreation and fitness workers',
       'Maintenance and repair workers, general',
       'Nonfarm animal caretakers',
       'Hotel, motel, and resort desk clerks',
       'Industrial and refractory machinery mechanics',
       'Locksmiths and safe repairers', 'Maids and housekeeping cleaners',
       'Hairdressers, hairstylists, and cosmetologists',
       'Janitors and building cleaners', 'Sewing machine operators',
       'Lawyers, Judges, magistrates, and other judicial workers',
       'Other life, physical, and social science technicians',
       'General and operations managers',
       'Court, municipal, and license clerks',
       'Stationary engineers and boiler operators',
       'Water and liquid waste treatment plant and system operators',
       'Taxi drivers and chauffeurs',
       'Miscellaneous community and social service specialists',
       'First-line supervisors/managers of police and detectives',
       'Bailiffs, correctional officers, and jailers',
       'Child care workers', 'Mining machine operators',
       'Small engine mechanics',
       'Reservation and transportation ticket agents and travel clerks',
       'Purchasing agents, except wholesale, retail, and farm products',
       'Marketing and sales managers',
       'Preschool and kindergarten teachers',
       'Other teachers and instructors',
       'Engineering technicians, except drafters', 'Medical scientists',
       'First-line supervisors/managers of food preparation and serving workers',
       'Electrical and electronics repairers, industrial and utility',
       'Automotive body and related repairers',
       'Loan counselors and officers',
       'Advertising and promotions managers', 'Education administrators',
       'Wholesale and retail buyers, except farm products', 'Bartenders',
       'Inspectors, testers, sorters, samplers, and weighers', 'Dentists',
       'Logisticians',
       'Crushing, grinding, polishing, mixing, and blending workers',
       'Highway maintenance workers',
       'Electric motor, power tool, and related repairers',
       'Biological scientists',
       'Miscellaneous vehicle and mobile equipment mechanics, installers, and repairers',
       'Postal service clerks',
       'Network and computer systems administrators',
       'Food service managers', 'Bakers',
       'Aircraft mechanics and service technicians',
       'Weighers, measurers, checkers, and samplers, recordkeeping',
       'Library technicians', 'Dishwashers',
       'Refuse and recyclable material collectors',
       'Real estate brokers and sales agents',
       'Claims adjusters, appraisers, examiners, and investigators',
       'Information and record clerks, all other', 'Sheet metal workers',
       'Medical assistants and other healthcare support occupations',
       'Industrial truck and tractor operators', 'Psychologists',
       'Bus drivers', 'Geological and petroleum technicians',
       'Insurance underwriters',
       'Models, demonstrators, and product promoters',
       'Construction managers',
       'Credit authorizers, checkers, and clerks',
       'Physical therapist assistants and aides',
       'Gaming services workers', 'Management analysts',
       'Cost estimators', 'Pharmacists',
       'Property, real estate, and community association managers',
       'Packers and packagers, hand', 'Librarians', 'Physical therapists',
       'Aerospace engineers',
       'Supervisors, transportation and material moving workers',
       'Dining room and cafeteria attendants and bartender helpers',
       'News analysts, reporters and correspondents',
       'Subway, streetcar, and other rail transportation workers',
       'Plasterers and stucco masons',
       'Sales and related workers, all other',
       'First-line supervisors/managers of housekeeping and janitorial workers',
       'Computer and information systems managers',
       'Securities, commodities, and financial services sales agents',
       'Computer, automated teller, and office machine repairers',
       'Counter and rental clerks',
       'Aircraft pilots and flight engineers',
       'Industrial engineers, including health and safety',
       'Emergency medical technicians and paramedics',
       'Electrical and electronic engineers', 'Transportation attendants',
       'Public relations specialists',
       'Miscellaneous legal support workers',
       'Billing and posting clerks and machine operators',
       'Miscellaneous media and communication workers',
       'Word processors and typists',
       'Other installation, maintenance, and repair workers',
       'Electronic home entertainment equipment installers and repairers',
       'Network systems and data communications analysts',
       'Door-to-door sales workers, news and street vendors, and related workers',
       'Chefs and head cooks', 'Miscellaneous agricultural workers ',
       'Packaging and filling machine operators and tenders',
       'Musicians, singers, and related workers',
       'Metalworkers and plastic workers, all other',
       'Grounds maintenance workers',
       'Clinical laboratory technologists and technicians',
       'Automotive service technicians and mechanics',
       'Other business operations specialists',
       'Market and survey researchers',
       'Administrative services managers',
       'Drywall installers, ceiling tile installers, and tapers',
       'Postal service mail carriers', 'Economists',
       'Licensed practical and licensed vocational nurses',
       'Conservation scientists and foresters',
       'Computer software engineers', 'Tellers',
       'Pumping station operators', 'File Clerks',
       'Statistical assistants',
       'Radio and telecommunications equipment installers and repairers',
       'Food servers, nonrestaurant', 'Dietitians and nutritionists',
       'Compliance officers, except agriculture, construction, health and safety, and transportation',
       'Office and administrative support workers, all other',
       'Photographers', 'Announcers', 'Insurance sales agents',
       'Couriers and messengers', 'Dental assistants',
       'Heavy vehicle and mobile equipment service technicians and mechanics',
       'Writers and authors', 'Computer operators',
       'Mechanical engineers', 'Order clerks',
       'Industrial production managers', 'Technical writers',
       'Meter readers, utilities', 'Physical scientists, all other',
       'Producers and directors',
       'Sales representatives, services, all other',
       'Construction and building inspectors', 'Financial analysts',
       'Electrical, electronics, and electromechanical assemblers',
       'First-line supervisors/managers of personal service workers',
       'Miscellaneous personal appearance workers',
       'Miscellaneous entertainment attendants and related workers',
       'Insurance claims and policy processing clerks',
       'Library assistants, clerical', 'Clergy',
       'Directors, religious activities and education',
       'Tax examiners, collectors, and revenue agents',
       'Production, planning, and expediting clerks',
       'Detectives and criminal investigators',
       'Computer hardware engineers',
       'Painters, construction and maintenance', 'Actors',
       'Interviewers, except eligibility and loan',
       'Other transportation workers ',
       'Motor vehicle operators, all other',
       'Hosts and hostesses, restaurant, lounge, and coffee shop',
       'First-line supervisors/managers of gaming workers',
       'Computer support specialists',
       'Human resources assistants, except payroll and timekeeping',
       'Broadcast and sound engineering technicians and radio operators',
       'Counter attendants, cafeteria, food concession, and coffee shop',
       'Septic tank servicers and sewer pipe cleaners',
       'Procurement clerks', 'Environmental scientists and geoscientists',
       'Travel agents', 'Physician assistants', 'Upholsterers',
       'Purchasing managers', 'Engineering managers',
       'Chemical technicians',
       'First-line supervisors/managers of landscaping, lawn service, and groundskeeping workers',
       'Drafters', 'Transportation, storage, and distribution managers',
       'Telephone operators', 'Therapists, all other',
       'Medical, dental, and ophthalmic laboratory technicians',
       'Graders and sorters, agricultural products',
       'Payroll and timekeeping clerks', 'Veterinarians',
       'Supervisors, protective service workers, all other',
       'Construction laborers', 'Advertising sales agents',
       'New accounts clerks',
       'Photographic process workers and processing machine operators',
       'Diagnostic related technologists and technicians',
       'Artists and related workers', 'Telemarketers',
       'Respiratory therapists',
       'Coin, vending, and amusement machine servicers and repairers',
       'Fire fighters', 'Operations research analysts',
       'Architects, except naval',
       'Marine engineers and naval architects',
       'Lifeguards and other protective service workers',
       'Chemical processing machine setters, operators, and tenders',
       'Telecommunications line installers and repairers', 'Millwrights',
       'Editors', 'Bookbinders and bindery workers',
       'Food and tobacco roasting, baking, and drying machine operators and tenders',
       'Occupational therapists', 'Actuaries', 'Petroleum engineers',
       'Roofers', 'Eligibility interviewers, government programs',
       'Sales engineers', 'Structural metal fabricators and fitters',
       'Tool and die makers', 'Animal breeders', 'Fish and game wardens',
       'Air traffic controllers and airfield operations specialists',
       'Derrick, rotary drill, and service unit operators, oil, gas, and mining',
       'Lodging managers',
       'Food preparation and serving related workers, all other',
       'Textile, apparel, and furnishings workers, all other',
       'Archivists, curators, and museum technicians',
       'Communications equipment operators, all other',
       'Service station attendants', 'Chemists and materials scientists',
       'Meeting and convention planners',
       'Personal care and service workers, all other ',
       'Funeral service workers', 'Human resources managers',
       'Religious workers, all other',
       'Surveyors, cartographers, and photogrammetrists',
       'Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic',
       'Riggers',
       'Television, video, and motion picture camera operators and editors',
       'Transportation inspectors',
       'Pressers, textile, garment, and related materials',
       'Painting workers', 'Brickmasons, blockmasons, and stonemasons',
       'Dental hygienists', 'Crossing guards',
       'Private detectives and investigators',
       'Other education, training, and library workers', 'Statisticians',
       'Appraisers and assessors of real estate',
       'Database administrators',
       'Miscellaneous social scientists and related workers',
       'Natural sciences managers', 'Environmental engineers',
       'Mail clerks and mail machine operators, except postal service',
       'Tour and travel guides', 'Financial specialists, all other',
       'Astronomers and physicists', 'Cargo and freight agents',
       'Machine feeders and offbearers', 'Materials engineers',
       'Cutting workers', 'Funeral directors', 'Home appliance repairers',
       'Jewelers and precious stone and metal workers',
       'Laundry and dry-cleaning workers', 'Helpers, construction trades',
       'Tax prepares',
       'Miscellaneous health technologists and technicians',
       'First-line supervisors/managers of fire fighting and prevention workers',
       'Security and fire alarm systems installers',
       'Locomotive engineers and operators', 'Recreational therapists',
       'Parking lot attendants',
       'Power plant operators, distributors, and dispatchers',
       'Entertainers and performers, sports and related workers, all other',
       'Baggage porters, bellhops, and concierges', 'Insulation workers',
       'Control and valve installers and repairers',
       'Railroad conductors and yardmasters', 'Public relations managers',
       'Chemical engineers',
       'Precision instrument and equipment repairers', 'Job printers',
       'Lathe and turning machine tool setters, operators, and tenders, metal and plastic',
       'Miscellaneous construction and related workers',
       'Roof bolters, mining',
       'Sawing machine setters, operators, and tenders, wood',
       'Automotive glass installers and repairers', 'Fence erectors',
       'Cabinetmakers and bench carpenters',
       'Office machine operators, except computer',
       'Paving, surfacing, and tamping equipment operators',
       'Agricultural and food science technicians',
       'Farm, ranch, and other agricultural managers',
       'Ship and boat captains and operators',
       'Extruding, forming, pressing, and compacting machine setters, operators, and tenders',
       'Financial examiners', 'Miscellaneous plant and system operators',
       'Molders and molding machine setters, operators, and tenders, metal and plastic',
       'Conveyor operators and tenders',
       'Tailors, dressmakers, and sewers', 'Helpers--production workers',
       'Rail-track laying and maintenance equipment operators',
       'Prepress technicians and workers',
       'Agricultural and food scientists', 'Boilermakers', 'Audiologists',
       'Material moving workers, all other',
       'Paper goods machine setters, operators, and tenders',
       'Logging workers', 'Computer control programmers and operators',
       'Engine and other machine assemblers', 'Credit analysts',
       'Tool grinders, filers, and sharpeners',
       'Manufactured building and mobile home installers',
       'Model makers and patternmakers, metal and plastic',
       'Woodworkers, all other',
       'Helpers--installation, maintenance, and repair workers ',
       'Roustabouts, oil and gas',
       'Cementing and gluing machine operators and tenders',
       'Dredge, excavating, and loading machine operators',
       'Purchasing agents and buyers, farm products', 'Budget analysts',
       'Furnace, kiln, oven, drier, and kettle operators and tenders',
       'First-line supervisors/managers of correctional officers',
       'Ushers, lobby attendants, and ticket takers',
       'Earth drillers, except oil and gas', 'Other extraction workers',
       'Cleaning, washing, and metal pickling equipment operators and tenders',
       'Elevator installers and repairers', 'Fire inspectors',
       'Plating and coating machine setters, operators, and tenders, metal and plastic',
       'Food cooking machine operators and tenders',
       'Animal control workers', 'Furniture finishers',
       'Woodworking machine setters, operators, and tenders, except sawing',
       'Textile knitting and weaving machine setters, operators, and tenders',
       'Gaming managers', 'Helpers--extraction workers',
       'Dancers and choreographers', 'Glaziers',
       'Atmospheric and space scientists', 'Semiconductor processors',
       'Etchers and engravers', 'Biological technicians',
       'Switchboard operators, including answering service',
       'Molders, shapers, and casters, except metal and plastic',
       'Pest control workers',
       'Aircraft structure, surfaces, rigging, and systems assemblers',
       'Occupational therapist assistants and aides',
       'Agents and business managers of artists, performers, and athletes',
       'Parking enforcement workers', 'Sailors and marine oilers',
       'Maintenance workers, machinery', 'Correspondence clerks',
       'Shuttle car operators',
       'Postal service mail sorters, processors, and processing machine operators',
       'Urban and regional planners',
       'Fishers and related fishing workers', 'Avionics technicians',
       'Shoe machine operators and tenders', 'Desktop publishers',
       'Textile bleaching and dyeing machine operators and tenders',
       'Optometrists',
       'Ambulance drivers and attendants, except emergency medical technicians',
       'Explosives workers, ordnance handling experts, and blasters',
       'Reinforcing iron and rebar workers', 'Nuclear engineers',
       'Agricultural engineers',
       'Electronic equipment installers and repairers, motor vehicles',
       'Health diagnosing and treating practitioners, all other',
       'Proofreaders and copy markers', 'Podiatrists',
       'Hunters and trappers', 'Tire builders',
       'Signal and track switch repairers', 'Brokerage clerks',
       'Textile cutting machine setters, operators, and tenders',
       'Drilling and boring machine tool setters, operators, and tenders, metal and plastic ',
       'Animal trainers', 'Bridge and lock tenders',
       'Motion picture projectionists',
       'Metal furnace and kiln operators and tenders',
       'Shoe and leather workers and repairers',
       'Rolling machine setters, operators, and tenders, metal and plastic',
       'Biomedical engineers', 'Gaming cage workers',
       'Mining and geological engineers, including mining safety engineers',
       'Milling and planing machine setters, operators, and tenders, metal and plastic',
       'Chiropractors', 'Lay-out workers, metal and plastic',
       'Ship engineers', 'Forest and conservation workers',
       'Multiple machine tool setters, operators, and tenders, metal and plastic ',
       'Mathematicians',
       'Electrical and electronics installers and repairers, transportation equipment',
       'Pile-driver operators',
       'Heat treating equipment setters, operators, and tenders, metal and plastic',
       'Radiation therapists', 'Sociologists', 'Agricultural inspectors',
       'Cooling and freezing equipment operators and tenders',
       'Tank car, truck, and ship loaders',
       'Railroad brake, signal, and switch operators',
       'Miscellaneous mathematical science occupations',
       'Extruding and drawing machine setters, operators, and tenders, metal and plastic',
       'Forging machine setters, operators, and tenders, metal and plastic',
       'Transit and railroad police',
       'Textile winding, twisting, and drawing out machine setters, operators, and tenders',
       'Fabric and apparel patternmakers', 'Commercial divers',
       'Extruding and forming machine setters, operators, and tenders, synthetic and glass fibers',
       'Hoist and winch operators',
       'Media and communication equipment workers, all other',
       'Paperhangers', 'Nuclear technicians', 'First-line', 'Secondary',
       'Customer', 'Nursing,', 'Interviewers,', 'Insurance',
       'Postsecondary', 'Computer', 'Receptionists', 'Secretaries',
       'Medical', 'Grounds', 'Construction', 'Child', 'Paralegals',
       'Managers,', 'Preschool', 'Retail', 'Human', 'Printing',
       'Registered', 'Elementary', 'Miscellaneous', 'Sales', 'Tax',
       'Social', 'General', 'Architects,', 'Education', 'Postal',
       'Mining', 'File', 'Welding,', 'Electrical', 'Laborers', 'Maids',
       'Driver/sales', 'Shipping,', 'Health', 'Bailiffs,', 'Opticians,',
       'Personal', 'Teacher', 'Electrical,', 'Nurse',
       'Telecommunications', 'Clinical', 'Bus', 'Parts', 'Loan',
       'Cleaners', 'Billing', 'Stock', 'Helpers,', 'JanitorsX', 'Agents',
       'Waiters', 'Writers', 'Butchers', 'Probation', 'Licensed',
       'Accountants', 'IndustrialX', 'Packers', 'Marketing', 'Athletes,',
       'Metal', 'Food', 'Control', 'Hotel,', 'Financial', 'Residential',
       'Laundry', 'Locksmiths', 'Security', 'Water', 'Lodging',
       'Compliance', 'Stationary', 'LifeguardsX', 'Procurement',
       'Supervisors,', 'Massage', 'Hairdressers,', 'Aircraft',
       'Bookkeeping,', 'Civil', 'Carpet,', 'Inspectors,', 'Office',
       'Computer,', 'Pumping', 'Painters,', 'Eligibility', 'Service',
       'Operating', 'Industrial', 'Textile', 'Helpers--installation,',
       'Therapists,', 'Crushing,', 'Ushers,', 'Police', 'Other',
       'Weighers,', 'Library', 'Securities,', 'Engineering',
       'Administrative', 'Biological', 'Refuse', 'Lawyers,', 'Budget',
       'Agricultural', 'Advertising', 'Automotive', 'Physician', 'Public',
       'Engineers,', 'Wholesale', 'Insulation', 'Real', 'Property,',
       'Credit', 'OtherXX', 'Physical', 'Gaming', 'Management', 'Drywall',
       'Chefs', 'Chief', 'Counter', 'News', 'Occupational', 'Cement',
       'Emergency', 'Special', 'Network', 'Mechanical', 'Training',
       'Heating,', 'Pest', 'Fire', 'SoftwareX', 'Combined', 'OtherX',
       'Physicians', 'Morticians,', 'Claims', 'Farmers,',
       'Transportation,', 'Phlebotomists', 'Packaging', 'Detectives',
       'Production', 'Business', 'Speech-language', 'Chemical',
       'Respiratory', 'Tool', 'Order', 'Material', 'Grinding,', 'Heavy',
       'Extruding,', 'Medical,', 'Radio', 'Dental', 'Dining', 'Couriers',
       'Nonfarm', 'Producers', 'Environmental', 'Sewing', 'Maintenance',
       'Data', 'Word', 'Meter', 'Pipelayers,', 'Hosts', 'Bill',
       'Musicians,', 'Operations', 'Diagnostic', 'Recreation', 'Small',
       'Mail', 'Electronic', 'Information', 'Parking', 'Travel',
       'Technical', 'Fabric', 'Cutting', 'Purchasing', 'Cost', 'Taxi',
       'Reservation', 'Appraisers', 'Database', 'Flight', 'Door-to-door',
       'Market', 'Heat', 'Metalworkers', 'Artists', 'Brickmasons,',
       'Meeting,', 'Precision', 'Court,', 'Helpers--production',
       'Payroll', 'Marine', 'Graders', 'Astronomers', 'Cleaning,',
       'Baggage', 'Production,', 'Web', 'Fundraisers', 'Atmospheric',
       'Animal', 'Air', 'Dredge,', 'Home', 'Dietitians', 'Aerospace',
       'Chemists', 'Switchboard', 'Plating', 'Crossing', 'Telephone',
       'Surveyors,', 'Archivists,', 'Compensation,', 'Models,', 'Urban',
       'Tour', 'Broadcast', 'Ship', 'Paper', 'ElectricalX', 'Pressers,',
       'Transportation', 'Jewelers', 'Etchers', 'Sailors', 'Molders',
       'FuneralXX', 'Power', 'Logging', 'Painting', 'Textile,', 'Sheet',
       'Motor', 'MiscellaneousX', 'Photographic', 'Cutting,', 'Highway',
       'Brokerage', 'Railroad', 'Structural', 'New', 'Prepress',
       'Subway,XX', 'Crane', 'Hazardous', 'Fence', 'Woodworking',
       'Sawing', 'Directors,', 'Conveyor', 'Print', 'Tailors,', 'Coin,',
       'Fishers', 'Veterinary', 'Commercial', 'Materials',
       'Cabinetmakers', 'Proofreaders', 'Nuclear', 'Rolling',
       'Biomedical', 'Shoe', 'Model', 'Multiple', 'Locomotive',
       'Avionics', 'Private', 'Derrick,', 'Recreational', 'Explosives',
       'Cementing', 'Entertainers', 'Dancers', 'Engine', 'Surveying',
       'Geological', 'Fish', 'Elevator', 'Conservation', 'Transit',
       'Pharmacy', 'Manufactured', 'Cooling', 'Statistical', 'Machine',
       'Tire', 'Religious', 'Furnace,', 'Roustabouts,', 'Hoist',
       'Ambulance', 'Lathe', 'Judicial', 'Woodworkers,', 'Septic',
       'Paving,', 'Compensation', 'Petroleum', 'Earth', 'Molders,',
       'Correspondence', 'Cargo', 'Roof', 'Electric', 'Signal', 'Media',
       'Television,', 'Plasterers', 'Semiconductor', 'Drilling', 'Survey',
       'Rail-track', 'Funeral', 'Desktop', 'Bridge', 'Forest',
       'Radiation', 'Helpers--extraction', 'Lay-out', 'Motion', 'Solar',
       'Natural', 'Forging', 'Pile-driver', 'Extruding', 'Furniture',
       'Tank', 'Communications', 'Exercise', 'Reinforcing', 'Milling',
       'Shuttle', 'Wind', 'Hunters', 'Lawyers', 'Tax preparers']

with open('occ.pkl', 'wb') as file:
    pickle.dump(occ, file)